#!/bin/bash
set -eu

HERE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
SOURCE_DIR="${HERE_DIR}/source"

pushd "${SOURCE_DIR}"

CFLAGS="-static ${CFLAGS:-}" CXXFLAGS="-static ${CXXFLAGS:-}" ./configure
